# Generated by Django 4.2.27 on 2025-12-13 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_projectcomponent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='component',
            name='svg',
            field=models.FileField(upload_to='components/'),
        ),
    ]
